<?php
/**
 * ARCHITECTURAL DOCBLOCK
 * 
 * File: pages/apps/cipher/rules.php
 * Path: /apps/cipher/rules
 * 
 * CORE RESPONSIBILITY:
 * Renders the "Decryption Protocols" (Rules) page for the Cipher mini-game.
 * Explains the game mechanics, difficulty tiers, and feedback symbols used
 * in the Mastermind-style deduction game.
 * 
 * LORE CONTEXT:
 * - Framed as "Standard Operating Procedures for Signal Analysis" within the
 *   Stardust Engine universe.
 * - Describes different frequency bands (Calibration, Orbital, Deep Space, Horizon)
 *   corresponding to game difficulties.
 * 
 * UI/UX & STYLING ARCHITECTURE:
 * - Purely presentation HTML utilizing Bootstrap 5 cards, tables, and alert components.
 * - Relies on Phosphor Icons (`ph ph-crosshairs`, `ph ph-gauge`, etc.) for visual hierarchy.
 * - Uses responsive design (`.table-responsive`) to ensure readability on mobile devices.
 * 
 * DEPENDENCIES & INCLUSIONS:
 * - Designed as a partial to be injected into a parent layout/router.
 * - Links back to the main application (`/apps/cipher`).
 * 
 * MAINTENANCE NOTES:
 * - If game mechanics (e.g., number of digits, repeat rules) change in the JavaScript logic,
 *   ensure this documentation is updated to match.
 * - This file does not contain PHP logic; it is a static HTML partial executing in a PHP environment.
 */
?>
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="text-center mb-5">
                <h1 class="display-5 fw-bold text-primary">
                    <i class="ph ph-book-sparkles me-2"></i>Decryption Protocols
                </h1>
                <p class="lead text-body-secondary">
                    Standard Operating Procedures for Signal Analysis
                </p>
            </div>

            <div class="card shadow-sm mb-4 border-0 bg-body-tertiary">
                <div class="card-body p-4">
                    <h4 class="card-title fw-bold mb-3">
                        <i class="ph ph-crosshairs me-2 text-danger"></i>Mission Objective
                    </h4>
                    <p class="card-text">
                        A rogue signal has been detected. Your goal is to decrypt the <strong>Secret Code</strong> generated by the system (or set by a rival agent). You must deduce the exact sequence of digits through logic and pattern recognition.
                    </p>
                </div>
            </div>

            <div class="card shadow-sm mb-4 border-0 bg-body-tertiary">
                <div class="card-body p-4">
                    <h4 class="card-title fw-bold mb-3">
                        <i class="ph ph-sliders-up me-2 text-info"></i>Signal Classifications
                    </h4>
                    <p class="mb-4">The Stardust Engine operates on four distinct frequency bands. Ensure you know which protocol is active.</p>
                    
                    <div class="table-responsive">
                        <table class="table table-bordered border-primary-subtle table-hover align-middle">
                            <thead class="table-light">
                                <tr>
                                    <th scope="col">Tier</th>
                                    <th scope="col">Frequency Range</th>
                                    <th scope="col">Signal Pattern</th>
                                    <th scope="col">Difficulty</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row" class="fw-bold text-success"><i class="ph ph-gauge me-2"></i>Calibration</th>
                                    <td>Digits 1 - 5</td>
                                    <td><span class="badge bg-success-subtle text-success-emphasis">Unique (No Repeats)</span></td>
                                    <td>Cadet</td>
                                </tr>
                                <tr>
                                    <th scope="row" class="fw-bold text-info"><i class="ph ph-satellite me-2"></i>Orbital</th>
                                    <td>Digits 1 - 6</td>
                                    <td><span class="badge bg-warning-subtle text-warning-emphasis">Repeats Allowed</span></td>
                                    <td>Standard</td>
                                </tr>
                                <tr>
                                    <th scope="row" class="fw-bold text-warning"><i class="ph ph-planet-ringed me-2"></i>Deep Space</th>
                                    <td>Digits 0 - 9</td>
                                    <td><span class="badge bg-success-subtle text-success-emphasis">Unique (No Repeats)</span></td>
                                    <td>Hard</td>
                                </tr>
                                <tr>
                                    <th scope="row" class="fw-bold text-danger"><i class="ph ph-galaxy me-2"></i>Horizon</th>
                                    <td>Digits 0 - 9</td>
                                    <td><span class="badge bg-warning-subtle text-warning-emphasis">Repeats Allowed</span></td>
                                    <td>Expert</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="card shadow-sm mb-4 border-0 bg-body-tertiary">
                <div class="card-body p-4">
                    <h4 class="card-title fw-bold mb-3">
                        <i class="ph ph-user-secret me-2 text-dark dark:text-light"></i>Classified Operations
                    </h4>
                    
                    <div class="d-flex align-items-start mb-3">
                        <i class="ph ph-eye-slash fa-2x me-3 text-body-secondary mt-1"></i>
                        <div>
                            <h6 class="fw-bold mb-1">Stealth Protocol</h6>
                            <p class="small text-body-secondary mb-0">
                                When enabled, the <strong>Logic Analysis Log</strong> is encrypted (hidden). You will receive only the raw symbol output (+/-) and must deduce the meaning without the computer's textual explanation.
                            </p>
                        </div>
                    </div>

                    <div class="d-flex align-items-start">
                        <i class="ph ph-eye fa-2x me-3 text-body-secondary mt-1"></i>
                        <div>
                            <h6 class="fw-bold mb-1">Target Visibility</h6>
                            <p class="small text-body-secondary mb-0">
                                The Secret Code is masked by default to allow for "Hot Seat" play (where one person types the code and another guesses). Click the <strong>Eye Icon</strong> inside the input field to peek at the target signal.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card shadow-sm mb-4 border-primary">
                <div class="card-header bg-primary text-white">
                    <i class="ph ph-magnifying-glass-chart me-2"></i>Reading the Feedback
                </div>
                <div class="card-body p-4 bg-body-tertiary">
                    
                    <div class="alert alert-warning d-flex align-items-center mb-4" role="alert">
                        <i class="ph ph-sort-amount-down fa-2x me-3"></i>
                        <div>
                            <strong>Priority Sorting:</strong> The Stardust Engine always displays <strong>(+)</strong> symbols first.
                            <br>
                            <small>The position of a symbol in the result does <em>not</em> correspond to the position of the digit in your guess.</small>
                        </div>
                    </div>

                    <p>After every guess, the system returns a set of symbols:</p>
                    
                    <div class="d-flex align-items-center mb-4 p-3 bg-body border rounded">
                        <div class="display-6 fw-bold text-success me-4 ps-2">+</div>
                        <div>
                            <h5 class="fw-bold text-success mb-1">Signal Locked (Plus)</h5>
                            <p class="mb-0 small text-body-secondary">You have a correct number in the <strong>correct</strong> spot.</p>
                        </div>
                    </div>

                    <div class="d-flex align-items-center mb-3 p-3 bg-body border rounded">
                        <div class="display-6 fw-bold text-warning me-4 ps-3">-</div>
                        <div>
                            <h5 class="fw-bold text-warning mb-1">Signal Detected (Minus)</h5>
                            <p class="mb-0 small text-body-secondary">You have a correct number, but it is in the <strong>wrong</strong> spot.</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="d-grid gap-2">
                <a href="/apps/cipher" class="btn btn-outline-primary btn-lg">
                    <i class="ph ph-arrow-left me-2"></i>Return to Decryptor
                </a>
            </div>

        </div>
    </div>
</div>